efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    300MiB
    minimumSize:        32MiB
    label:              "EFI"

userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    - file      # To swap file instead of partition

swapPartitionName:      swap

luksGeneration: luks1

drawNestedPartitions:   true

alwaysShowPartitionLabels: true

initialPartitioningChoice: none

initialSwapChoice: suspend

defaultPartitionTableType: msdos

requiredPartitionTableType:
    - msdos
    - gpt

defaultFileSystemType:  "ext4"
availableFileSystemTypes:  ["ext4","btrfs","f2fs","xfs"]
