---
backend: pacman

pacman:
    num_retries: 0
    disable_download_timeout: false
    needed_only: false
    handle_keyrings: true
    copy_pacconf: true
    requirements:
      - dest: /etc
        mode: "0o755"
      - dest: /var
        mode: "0o755"
      - dest: /var/cache
        mode: "0o755"
      - dest: /var/cache/pacman
        mode: "0o755"
      - dest: /var/cache/pacman/pkg
        mode: "0o755"
      - dest: /var/lib
        mode: "0o755"
      - dest: /var/lib/pacman
        mode: "0o755"
    keyrings:
      - artix

base_init: elogind

operations:
  - install:
    - base
