---
groupsUrl:
    - https://gitea.artixlinux.org/artix/netinstall-data/raw/branch/master/netinstall.yaml
    - file:///etc/calamares/modules/netinstall.yaml

required: false

# To support multiple instances of this module,
# some strings are configurable and translatable here.
# Sub-keys under *label* are used for the user interface.
#  - *sidebar* This is the name of the module in the progress-tree / sidebar
#   in Calamares.
#  - *title* This is displayed above the list of packages.
# If no *sidebar* values are provided, defaults to "Package selection"
# and existing translations. If no *title* values are provided, no string
# is displayed.
#
# Translations are handled through `[ll]` notation, much like in
# `.desktop` files. The string associated with `key[ll]` is used for
# *key* when when the language *ll* (language-code, like *nl* or *en_GB*
# or *ja*) is used.
#
# The following strings are **already** known to Calamares and can be
# listed here in *untranslated* form (e.g. as value of *sidebar*)
# without bothering with the translations: they are picked up from
# the regular translation framework:
#  - "Package selection"
#  - "Office software"
#  - "Office package"
#  - "Browser software"
#  - "Browser package"
#  - "Web browser"
#  - "Kernel"
#  - "Services"
#  - "Login"
#  - "Desktop"
#  - "Applications"
#  - "Communication"
#  - "Development"
#  - "Office"
#  - "Multimedia"
#  - "Internet"
#  - "Theming"
#  - "Gaming"
#  - "Utilities"
# Other strings should follow the translations format.
label:
    sidebar: "Package selection"
    # sidebar[nl]: "Pakketkeuze"
    # sidebar[en_GB]: "Package choice"
    # sidebar[ja]: "知りません"  # "I don't know"
    # title: "Office Package"
    # title[nl]: "Kantoorsoftware"


